"use client";
import { motion } from "framer-motion";
import { Sparkles } from "lucide-react";

export default function InsightPanel({ insight }: { insight: string }) {
  const paragraphs = insight.split(/\n+/).filter(Boolean);

  return (
    <motion.div
      initial={{ opacity: 0, y: 10 }}
      animate={{ opacity: 1, y: 0 }}
      className="rounded-xl border border-[#c7d2fe] bg-[#eef2ff] p-5 sm:p-6 space-y-4"
    >
      <div className="flex items-center gap-2 text-[#4338ca]">
        <Sparkles className="h-4 w-4" />
        <span className="text-sm font-semibold">Executive Brief — Generated by Gemini 2.5 Flash</span>
      </div>
      <div className="space-y-3">
        {paragraphs.map((p, i) => (
          <p key={i} className="text-[#374151] text-sm leading-relaxed">{p}</p>
        ))}
      </div>
    </motion.div>
  );
}
