"use client";
import { useState, useEffect } from "react";
import { motion } from "framer-motion";
import { Sparkles, Printer, Loader2, AlertTriangle, CheckCircle, ArrowRight } from "lucide-react";
import Link from "next/link";
import InsightPanel from "@/components/InsightPanel";
import type { MetricsSummary } from "@/types";

const f1Color = (f1: number) =>
  f1 >= 0.8 ? "text-[#047857]" : f1 >= 0.65 ? "text-[#b45309]" : "text-[#be123c]";

export default function InsightsPage() {
  const [metrics, setMetrics] = useState<MetricsSummary | null>(null);
  const [insight, setInsight] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [generatedAt, setGeneratedAt] = useState<string | null>(null);
  const [fallback, setFallback] = useState(false);

  useEffect(() => {
    if (typeof window !== "undefined") {
      const stored = localStorage.getItem("qa_metrics");
      if (stored) {
        try { setMetrics(JSON.parse(stored)); } catch { /* ignore */ }
      }
    }
  }, []);

  // Locally-composed brief — guarantees output even if the API is unreachable.
  function localBrief(m: MetricsSummary): string {
    const flagged = m.by_reviewer.filter(r => r.needs_flag);
    const best = [...m.by_modality].sort((a, b) => b.f1 - a.f1)[0];
    const worst = [...m.by_modality].sort((a, b) => a.f1 - b.f1)[0];
    const acc = (m.overall_accuracy * 100).toFixed(1);

    const flagLine = flagged.length
      ? `${flagged.map(r => r.reviewer_id).join(", ")} ${flagged.length > 1 ? "fall" : "falls"} below the 60% accuracy threshold and ${flagged.length > 1 ? "require" : "requires"} immediate retraining.`
      : `No reviewer currently falls below the 60% retraining threshold.`;

    return [
      `Overall QA health stands at ${acc}% accuracy across ${m.total_reviews} reviewed decisions. ${best ? `The ${best.modality} modality is the strongest performer at an F1 of ${(best.f1 * 100).toFixed(1)}%, indicating reliable reviewer judgement in that channel.` : ""}`,
      `${worst ? `The ${worst.modality} modality is the weakest at an F1 of ${(worst.f1 * 100).toFixed(1)}%, posing the greatest moderation risk and warranting closer supervision.` : ""} ${flagLine}`,
      `Recommendation: route the flagged reviewers' decisions through a second-pass QA agent and prioritise targeted retraining on their weakest modality. Running this multi-agent pipeline continuously could reclaim an estimated 30–40% of manual QA hours while surfacing systematic errors far earlier than periodic manual audits.`,
    ].filter(Boolean).join("\n\n");
  }

  async function generateInsight() {
    if (!metrics) return;
    setLoading(true);
    setInsight(null);
    setFallback(false);
    try {
      const res = await fetch("/api/generate-insights", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ metrics }),
      });
      const data = await res.json();
      if (!res.ok || data.error || !data.insight) throw new Error(data.error || "Empty response");
      setInsight(data.insight);
      setGeneratedAt(data.generated_at);
    } catch (err) {
      // Never show a raw error during a live demo — fall back to a locally-composed brief.
      console.error(err);
      setInsight(localBrief(metrics));
      setGeneratedAt(new Date().toISOString());
      setFallback(true);
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="mx-auto max-w-7xl px-4 sm:px-6 py-8 sm:py-10 space-y-8">
      <div>
        <h1 className="text-2xl sm:text-3xl font-extrabold text-[#111827]">Leadership Brief</h1>
        <p className="text-[#6b7280] mt-1 text-sm sm:text-base">
          AI-synthesized executive summary from QA metrics, generated by Gemini 2.5 Flash.
        </p>
      </div>

      {!metrics && (
        <div className="rounded-xl border border-[#fde68a] bg-[#fffbeb] p-6 text-[#b45309] flex flex-col sm:flex-row sm:items-center gap-4">
          <div className="flex items-center gap-3">
            <AlertTriangle className="h-5 w-5 flex-shrink-0" />
            <p>No QA metrics found yet. Run the analysis on the Dashboard first.</p>
          </div>
          <Link
            href="/dashboard"
            className="inline-flex items-center justify-center gap-2 rounded-lg bg-[#4f46e5] hover:bg-[#4338ca] px-4 py-2 text-sm font-semibold text-white sm:ml-auto whitespace-nowrap"
          >
            Go to Dashboard <ArrowRight className="h-4 w-4" />
          </Link>
        </div>
      )}

      {metrics && (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6 md:gap-8">
          {/* Left: Metrics Summary */}
          <div className="space-y-6">
            <div className="rounded-xl border border-[#e5e7eb] bg-white p-5 sm:p-6 space-y-4 shadow-sm">
              <h2 className="text-lg font-semibold text-[#111827]">Metrics Summary</h2>

              <div>
                <p className="text-xs text-[#9ca3af] uppercase tracking-wider mb-3">Modality F1 Scores</p>
                <div className="space-y-2">
                  {metrics.by_modality.map((m) => (
                    <div key={m.modality} className="flex items-center justify-between">
                      <span className="capitalize text-sm text-[#374151]">{m.modality}</span>
                      <span className={`font-bold text-sm ${f1Color(m.f1)}`}>
                        {(m.f1 * 100).toFixed(1)}%
                      </span>
                    </div>
                  ))}
                </div>
              </div>

              <div className="border-t border-[#f1f3f5] pt-4">
                <p className="text-xs text-[#9ca3af] uppercase tracking-wider mb-3">Reviewer Status</p>
                <div className="space-y-2">
                  {metrics.by_reviewer.map((r) => (
                    <div key={r.reviewer_id} className="flex items-center justify-between">
                      <div className="flex items-center gap-2">
                        {r.needs_flag ? (
                          <AlertTriangle className="h-3 w-3 text-[#e11d48]" />
                        ) : (
                          <CheckCircle className="h-3 w-3 text-[#059669]" />
                        )}
                        <span className="text-sm text-[#374151]">{r.reviewer_id}</span>
                      </div>
                      <span className={`text-sm font-medium ${r.needs_flag ? "text-[#be123c]" : "text-[#374151]"}`}>
                        {(r.accuracy * 100).toFixed(1)}%
                        {r.needs_flag && <span className="ml-1 text-xs text-[#e11d48]">⚠ Flag</span>}
                      </span>
                    </div>
                  ))}
                </div>
              </div>

              <div className="border-t border-[#f1f3f5] pt-4 flex justify-between items-center">
                <span className="text-sm text-[#6b7280]">Overall Accuracy</span>
                <span className="text-xl font-extrabold text-[#4f46e5]">
                  {(metrics.overall_accuracy * 100).toFixed(1)}%
                </span>
              </div>
            </div>
          </div>

          {/* Right: Executive Brief */}
          <div className="space-y-4">
            <div className="flex items-center justify-between">
              <h2 className="text-lg font-semibold text-[#111827]">Executive Brief</h2>
              {insight && (
                <button
                  onClick={() => window.print()}
                  className="flex items-center gap-1.5 rounded-lg border border-[#e5e7eb] bg-white px-3 py-1.5 text-xs text-[#6b7280] hover:text-[#111827] transition-colors"
                >
                  <Printer className="h-3 w-3" /> Print / Export
                </button>
              )}
            </div>

            <button
              onClick={generateInsight}
              disabled={loading || !metrics}
              className="w-full flex items-center justify-center gap-2 rounded-xl bg-[#4f46e5] hover:bg-[#4338ca] disabled:opacity-50 disabled:cursor-not-allowed px-6 py-3 font-semibold text-white transition-all shadow-md"
            >
              {loading ? (
                <><Loader2 className="h-4 w-4 animate-spin" /> Insight Agent synthesizing...</>
              ) : (
                <><Sparkles className="h-4 w-4" /> Generate Executive Brief</>
              )}
            </button>

            {loading && (
              <motion.div
                initial={{ opacity: 0 }}
                animate={{ opacity: [0.4, 1, 0.4] }}
                transition={{ duration: 1.5, repeat: Infinity }}
                className="rounded-xl border border-[#c7d2fe] bg-white p-6 text-center"
              >
                <p className="text-[#4338ca] text-sm">Gemini 2.5 Flash is analyzing metrics and composing the executive brief...</p>
              </motion.div>
            )}

            {insight && !loading && (
              <>
                <InsightPanel insight={insight} />
                <p className="text-xs text-[#9ca3af] text-center">
                  {generatedAt && <>Generated {new Date(generatedAt).toLocaleString()} · </>}
                  {fallback ? "Composed locally from metrics (live model unavailable)" : "Google Gemini 2.5 Flash"}
                </p>
              </>
            )}
          </div>
        </div>
      )}
    </div>
  );
}
