"use client";
import { useState, useEffect } from "react";
import { motion } from "framer-motion";
import { Sparkles, Printer, Loader2, AlertTriangle, CheckCircle } from "lucide-react";
import InsightPanel from "@/components/InsightPanel";
import type { MetricsSummary } from "@/types";

const f1Color = (f1: number) =>
  f1 >= 0.8 ? "text-emerald-400" : f1 >= 0.65 ? "text-amber-400" : "text-red-400";

export default function InsightsPage() {
  const [metrics, setMetrics] = useState<MetricsSummary | null>(null);
  const [insight, setInsight] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [generatedAt, setGeneratedAt] = useState<string | null>(null);

  useEffect(() => {
    if (typeof window !== "undefined") {
      const stored = localStorage.getItem("qa_metrics");
      if (stored) setMetrics(JSON.parse(stored));
    }
  }, []);

  async function generateInsight() {
    if (!metrics) return;
    setLoading(true);
    setInsight(null);
    try {
      const res = await fetch("/api/generate-insights", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ metrics }),
      });
      const data = await res.json();
      if (data.error) throw new Error(data.error);
      setInsight(data.insight);
      setGeneratedAt(data.generated_at);
    } catch (err) {
      console.error(err);
      setInsight(`Error: ${err instanceof Error ? err.message : "Unknown error"}`);
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="mx-auto max-w-7xl px-6 py-10 space-y-8">
      <div>
        <h1 className="text-3xl font-extrabold text-slate-100">Leadership Brief</h1>
        <p className="text-slate-400 mt-1">
          AI-synthesized executive summary from QA metrics, generated by Gemini 2.5 Flash.
        </p>
      </div>

      {!metrics && (
        <div className="rounded-xl border border-amber-700/50 bg-amber-950/20 p-6 text-amber-400 flex items-center gap-3">
          <AlertTriangle className="h-5 w-5 flex-shrink-0" />
          <p>No QA metrics found. Please run the QA analysis on the Dashboard first.</p>
        </div>
      )}

      {metrics && (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
          {/* Left: Metrics Summary */}
          <div className="space-y-6">
            <div className="rounded-xl border border-slate-700 bg-slate-800 p-6 space-y-4">
              <h2 className="text-lg font-semibold text-slate-100">Metrics Summary</h2>

              <div>
                <p className="text-xs text-slate-500 uppercase tracking-wider mb-3">Modality F1 Scores</p>
                <div className="space-y-2">
                  {metrics.by_modality.map((m) => (
                    <div key={m.modality} className="flex items-center justify-between">
                      <span className="capitalize text-sm text-slate-300">{m.modality}</span>
                      <span className={`font-bold text-sm ${f1Color(m.f1)}`}>
                        {(m.f1 * 100).toFixed(1)}%
                      </span>
                    </div>
                  ))}
                </div>
              </div>

              <div className="border-t border-slate-700 pt-4">
                <p className="text-xs text-slate-500 uppercase tracking-wider mb-3">Reviewer Status</p>
                <div className="space-y-2">
                  {metrics.by_reviewer.map((r) => (
                    <div key={r.reviewer_id} className="flex items-center justify-between">
                      <div className="flex items-center gap-2">
                        {r.needs_flag ? (
                          <AlertTriangle className="h-3 w-3 text-red-400" />
                        ) : (
                          <CheckCircle className="h-3 w-3 text-emerald-400" />
                        )}
                        <span className="text-sm text-slate-300">{r.reviewer_id}</span>
                      </div>
                      <span className={`text-sm font-medium ${r.needs_flag ? "text-red-400" : "text-slate-300"}`}>
                        {(r.accuracy * 100).toFixed(1)}%
                        {r.needs_flag && <span className="ml-1 text-xs text-red-500">⚠ Flag</span>}
                      </span>
                    </div>
                  ))}
                </div>
              </div>

              <div className="border-t border-slate-700 pt-4 flex justify-between items-center">
                <span className="text-sm text-slate-400">Overall Accuracy</span>
                <span className="text-xl font-extrabold text-cyan-400">
                  {(metrics.overall_accuracy * 100).toFixed(1)}%
                </span>
              </div>
            </div>
          </div>

          {/* Right: Executive Brief */}
          <div className="space-y-4">
            <div className="flex items-center justify-between">
              <h2 className="text-lg font-semibold text-slate-100">Executive Brief</h2>
              {insight && (
                <button
                  onClick={() => window.print()}
                  className="flex items-center gap-1.5 rounded-lg border border-slate-600 px-3 py-1.5 text-xs text-slate-400 hover:text-slate-200 transition-colors"
                >
                  <Printer className="h-3 w-3" /> Print / Export
                </button>
              )}
            </div>

            <button
              onClick={generateInsight}
              disabled={loading || !metrics}
              className="w-full flex items-center justify-center gap-2 rounded-xl bg-cyan-600 hover:bg-cyan-500 disabled:opacity-50 disabled:cursor-not-allowed px-6 py-3 font-semibold text-white transition-all"
            >
              {loading ? (
                <><Loader2 className="h-4 w-4 animate-spin" /> Insight Agent synthesizing...</>
              ) : (
                <><Sparkles className="h-4 w-4" /> Generate Executive Brief</>
              )}
            </button>

            {loading && (
              <motion.div
                initial={{ opacity: 0 }}
                animate={{ opacity: [0.4, 1, 0.4] }}
                transition={{ duration: 1.5, repeat: Infinity }}
                className="rounded-xl border border-cyan-800/40 bg-slate-800 p-6 text-center"
              >
                <p className="text-cyan-400 text-sm">Gemini 2.5 Flash is analyzing metrics and composing executive brief...</p>
              </motion.div>
            )}

            {insight && !loading && (
              <>
                <InsightPanel insight={insight} />
                {generatedAt && (
                  <p className="text-xs text-slate-500 text-center">
                    Generated {new Date(generatedAt).toLocaleString()} · Google Gemini 2.5 Flash
                  </p>
                )}
              </>
            )}
          </div>
        </div>
      )}
    </div>
  );
}
